using Serilog;

namespace Web.Api.Bundels
{
    internal static class AppConfiguration
    {
        internal static async Task Configure(this WebApplication app)
        {
            await app.EnsureDatabasesUpToDate();

            app.UseSerilogRequestLogging();

            if (app.Environment.IsDevelopment())
            {
                app.MapOpenApi();

                // Swagger UI on /swagger, reading the document generated by MapOpenApi.
                app.UseSwaggerUI(options =>
                {
                    options.SwaggerEndpoint($"/openapi/{AppServiceRegistration.OpenApiDocumentName}.json", AppServiceRegistration.OpenApiDocumentTitle);
                    options.EnablePersistAuthorization();
                });
            }

            app.UseCors();

            app.UseHttpsRedirection();

            app.UseAuthentication();

            app.UseAuthorization();

            app.MapControllers();
        }
    }
}
