using Microsoft.AspNetCore.Rewrite;
using Serilog;

namespace Web.Api.Bundels
{
    internal static class AppConfiguration
    {
        private const string SwaggerRoutePrefix = "swagger";

        internal static async Task Configure(this WebApplication app)
        {
            await app.EnsureDatabasesUpToDate();
            await app.SeedDefaultAdmin();

            app.UseSerilogRequestLogging();

            if (app.Environment.IsDevelopment())
            {
                app.MapOpenApi();

                // Swagger UI on /swagger, reading the document generated by MapOpenApi.
                app.UseSwaggerUI(options =>
                {
                    options.RoutePrefix = SwaggerRoutePrefix;
                    options.SwaggerEndpoint($"/openapi/{AppServiceRegistration.OpenApiDocumentName}.json", AppServiceRegistration.OpenApiDocumentTitle);
                    options.EnablePersistAuthorization();
                });

                // The root URL "/" opens Swagger UI.
                app.UseRewriter(new RewriteOptions().AddRedirect("^$", SwaggerRoutePrefix));
            }

            app.UseCors();

            app.UseHttpsRedirection();

            app.UseAuthentication();

            app.UseAuthorization();

            app.MapControllers();
        }
    }
}
